require 'rubygems'
require 'httpclient'
require 'json'
require 'linkeddata'

require 'kasabi/api/lookup'
require 'kasabi/api/sparql'
require 'kasabi/api/search'
require 'kasabi/api/facet'
require 'kasabi/api/augment'